brew "asdf"
brew "autoconf"
brew "exercism"
brew "fswatch"
brew "gh"
brew "git"
brew "git-flow-avh"
brew "git-lfs"
brew "gpg"
brew "jq"
brew "nvm"
brew "openssl@1.1"
brew "pure"
brew "rename"
brew "the_silver_searcher"
brew "tmux"

tap "nexeck/homebrew-tmuxinator"
brew "nexeck/homebrew-tmuxinator/tmuxinator"

tap "stripe/stripe-cli"
brew "stripe/stripe-cli/stripe"
