# A rio theme for [jummi-dark](https://github.com/jcherven/jummidark.vim)
[colors]
background       = '#262626'
black            = '#1c1c1c'
blue             = '#af5fff'
cursor           = '#af8700'
cyan             = '#00d7d7'
foreground       = '#e4e4e4'
green            = '#00d7d7'
magenta          = '#af87ff'
red              = '#d7005f'
tabs             = '#6c6c6c'
tabs-active      = '#b2b2b2'
white            = '#8a8a8a'
yellow           = '#00ffaf'
dim-black        = '#303030'
dim-blue         = '#af5fff'
dim-cyan         = '#00d7d7'
dim-foreground   = '#b2b2b2'
dim-green        = '#00d7d7'
dim-magenta      = '#af87ff'
dim-red          = '#d7005f'
dim-white        = '#b2b2b2'
dim-yellow       = '#E6A003'
light-black      = '#4e4e4e'
light-blue       = '#af87ff'
light-cyan       = '#00d7d7'
light-foreground = '#ffffff'
light-green      = '#00d7d7'
light-magenta    = '#af87ff'
light-red        = '#d75f87'
light-white      = '#FFFfff'
light-yellow     = '#00ffaf'
